name: $(BuildDefinitionName) $(SourceBranchName) $(Date:yyyy-MM-dd)$(Rev:.rr)

# Triggers are overriden in ADO UI. Run this job manually on ADO. Requires the following
# variables to be set in UI (when creating a new pipeline from this file)
# publishUser
# publishUrl
trigger: none
pr: none

pool:
  vmImage: 'macOS-10.15'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean assembleRelease publish'
    options: '
      --continue 
      --stacktrace 
      --no-daemon 
      -Ppublish_user=$(publishUser)
      -Ppublish_pass=$(System.AccessToken)
      -Ppublish_url=$(publishUrl)'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
  displayName: 'Publish to artifact feed'
